<matlab>
figure;
hAxes = axes;
SWP = handles.expparams.sweeps(1);
x = SWP.sweepArray;
y = handles.Counter.AveragedData;                   
plot(x,y,'.-','Parent',hAxes);
title('Rabi @ 0dBm');
xlabel('Rabi Pulse Duration (s)');
ylabel('Counts');
figure;
hAxes = axes;
s = (y(:,3)-y(:,2))./(y(:,1)-y(:,2));              
plot(x,s,'.-','Parent',hAxes);
title('Referenced Rabi @ 0dBm');
xlabel('Rabi Pulse Duration (s)');
ylabel('Counts');
fitmodel = fittype('A*cos(2*pi*wnut*t)*exp(-t/T2)+C','ind','t','coeff',{'A','wnut','T2','C'});
opts = fitoptions(fitmodel);
opts.StartPoint = [0.5,8e6,1,0.5];
[fitresult,gof] = fit(x',s,fitmodel,opts);
disp(fitresult);
hold on;
plot(fitresult);
figure;
hAxes = axes;
[spec,freqs] = positiveFFT(s-mean(s),1/(x(2)-x(1)));
plot(freqs/1e6,abs(spec));
xlabel('Frequency (MHz)');
title('Rabi Flops Power Spectrum');
</matlab>